# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7be63cfc3e25f98ec363a2b3cd08712881ed0e820e9a6b519bcfe56cfebee8bde6e6e4742064649e161d13c7ef16609dfaeabb2ba8797ba142475c0fa853e3f7

test:
  secret_key_base: d712440a689dcf560f7453150f0f86845bd77ec1b364101354ab7d85e61e7a2a3dbe98834b9d5786b762f198ae2158189e6f6137c841dafe9c3059689988d534

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
